# http://hessian.caucho.com/doc/hessian-ws.html
# http://hessian.caucho.com/doc/hessian-serialization.html
require 'hessian2/class_wrapper'
require 'hessian2/client'
require 'hessian2/fault'
require 'hessian2/handler'
require 'hessian2/hessian_client'
require 'hessian2/type_wrapper'
require 'hessian2/version'
